version: 2
jobs:
    build:
        working_directory: ~/one-time-secret
        docker:
        - image: circleci/node:10.0
        steps:
        - checkout
        - restore_cache:
            key: v0-install-and-build-cache-{{ .Branch }}-{{ .Revision }}
        - run:
            name: Install dependencies
            command: npm install --pure-lockfile
        - run:
            name: Build project
            command: npm run build:test
        - save_cache:
            key: v0-install-and-build-cache-{{ .Branch }}-{{ .Revision }}
            paths:
                - dist
                - node_modules

    test:
        working_directory: ~/one-time-secret
        docker:
        - image: circleci/node:10.0
        steps:
        - checkout
        - restore_cache:
            key: v0-install-and-build-cache-{{ .Branch }}-{{ .Revision }}
        - run:
            name: Test for circular dependencies
            command: npm run circular
        - run:
            name: Check lint
            command: npm run lint
        - run:
            name: Refuse complex code.
            command: npm run complexity

workflows:
    version: 2
    build_test:
        jobs:
        - build
        - test:
            requires:
                - build
